spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://fis.cb4kk8iiuvdy.ap-south-1.rds.amazonaws.com:5432/fis'
    username: 'postgres'
    password: 'Admin12345'
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
        format_sql: false
  liquibase:
    change-log: 'classpath:db/liquibase-changelog-master.xml'
    contexts: 'test-data'
